auto: true
markdown: rdiscount
pygments: true
permalink: /blog/:title

organization: craftofelectronics
repos: tad265f12
pages_root: http://craftofelectronics.github.com/
github_root: https://github.com/craftofelectronics/

course: Craft of Electronics
sections: [["admin", "Admin", [[syllabus, "Syllabus"], [todo, "To Do"]]]]

license_url: http://creativecommons.org/licenses/by/3.0/
license_abbrev: CC BY-SA 3.0